"""Download the intermediate-artifact bundle from the HuggingFace Hub.

The figures and tables are regenerated by ``reproduce/`` from *intermediate
artifacts* (generations, guardrail classifications, representation/probe caches,
cut-rollout caches, annotator labels).  These are large and regenerable, so they
are hosted on the Hub rather than committed.  This module pulls them into
:data:`lrm_safety_deliberation.paths.ARTIFACTS_ROOT`, preserving the subtree layout the
``reproduce/`` scripts expect.

Two tiers:

* ``figures`` — the small/medium caches that let the CPU ``reproduce/`` scripts
  run without a GPU (a few GB).
* ``full``    — everything, including the multi-GB K=32 / K=100 rollouts and the
  representation tensors needed to *recompute* the caches from scratch.

Usage::

    python -m lrm_safety_deliberation.fetch_artifacts --list                 # show the manifest
    python -m lrm_safety_deliberation.fetch_artifacts --tier figures         # default
    python -m lrm_safety_deliberation.fetch_artifacts --tier full --repo org/name

The Hub repo id defaults to the env var ``LRM_SAFETY_ARTIFACTS_REPO`` (or a
placeholder).  Set it once the bundle has been uploaded.
"""

from __future__ import annotations

import argparse
import os

from .paths import ARTIFACTS_ROOT

# HuggingFace dataset repo holding the intermediate-artifact bundle.
DEFAULT_REPO = os.environ.get("LRM_SAFETY_ARTIFACTS_REPO", "narutatsuri/lrm_safety-artifacts")

# Each bundle: glob patterns (relative to the artifact tree), the cheapest tier
# that includes it, an approximate size, and the reproduce scripts that need it.
MANIFEST = [
    # --- behavioral ASR/ORR ---
    {"name": "asr_orr_base", "tier": "figures", "approx": "~1.6 GB",
     "patterns": ["eval_results/asr_orr_16k_K4/*/*/summary.json",
                  "eval_results/asr_orr_16k_K4/*/*/results.jsonl"],
     "consumers": ["tab_base_asr_orr"]},
    {"name": "asr_orr_summaries", "tier": "figures", "approx": "~5 MB",
     "patterns": ["eval_results/neurips_final/*/__fullpipe__/*/*/summary.json",
                  "eval_results/defenses_eval/*/__fullpipe__/*/*/summary.json"],
     "consumers": ["tab_defenses_asr_orr", "fig_defense_pareto"]},
    # --- representation geometry ---
    {"name": "valley_caches", "tier": "figures", "approx": "~50 MB",
     "patterns": ["eval_results/neurips_final/*/valley/explore_*.pt",
                  "eval_results/neurips_final_supplementary/*/valley/explore_*.pt"],
     "consumers": ["fig_refusal_valley", "fig_refusal_valley_supplementary"]},
    {"name": "kshop_caches", "tier": "figures", "approx": "~1 MB",
     "patterns": ["experiments/refusal_cliff/results/kshop_K20_user_content/norm_fisher_*.json",
                  "experiments/refusal_cliff/results/kshop_K20_user_content/bestpipe_pca100_c003.json"],
     "consumers": ["fig_prefill_decision"]},
    {"name": "prefill_reps", "tier": "full", "approx": "~30 GB",
     "patterns": ["eval_results/neurips_s16/*/representations/prefill_think_before/*.pt"],
     "consumers": ["tab_auroc_ci"]},
    {"name": "trace_reps", "tier": "full", "approx": "~200 GB",
     "patterns": ["eval_results/neurips_final/*/representations/**/*",
                  "experiments/refusal_cliff/artifacts/kshop_K20_user_content/**/*"],
     "consumers": ["(recompute valley_caches / kshop_caches)"]},
    # --- extended thinking (K=32) ---
    {"name": "k32_aggregate", "tier": "figures", "approx": "<1 MB",
     "patterns": ["experiments/nested_branching_variance/k32_full/analysis/data/asr_orr_within_by_cut.json"],
     "consumers": ["fig_extended_thinking", "fig_within_prefix_variance"]},
    {"name": "k32_classifications", "tier": "figures", "approx": "~3 GB",
     "patterns": ["eval_results/k32_full_pool/*/*/*/classifications_*.jsonl"],
     "consumers": ["fig_nothink_to_think", "fig_nothink_to_think_lenient", "fig_within_prefix_variance"]},
    {"name": "k32_rollouts", "tier": "full", "approx": "~110 GB",
     "patterns": ["eval_results/k32_full_pool/**/*", "eval_results/k32_nested_branching_full/**/*"],
     "consumers": ["(recompute k32_aggregate)"]},
    # --- causal cuts ---
    {"name": "cuts_caches", "tier": "figures", "approx": "~250 MB",
     "patterns": ["experiments/causal_cuts/rebuttal/m4_allcuts.jsonl",
                  "experiments/causal_cuts/rebuttal/m4_cuts.jsonl",
                  "experiments/causal_cuts/rebuttal/sig_cuts_enriched.jsonl",
                  "experiments/causal_cuts/rebuttal/m4_majority3.jsonl",
                  "experiments/causal_cuts/rebuttal/m4_training_defense_majority3.jsonl",
                  "experiments/causal_cuts/rebuttal/m4_inference_defense_majority3.jsonl",
                  "experiments/causal_cuts/rebuttal/m4_inference_defense_oscillation.json",
                  "experiments/causal_cuts/plots/finding4/f4_metrics.json"],
     "consumers": ["fig_thinking_causal", "tab_inference_defense_suppression", "fig_training_slopegraph"]},
    {"name": "cuts_rollouts", "tier": "full", "approx": "~80 GB",
     "patterns": ["experiments/causal_cuts/eval_results/**/*"],
     "consumers": ["(recompute cuts_caches; exact tab_inference_defense_suppression)"]},
    # --- IAA + slopegraph ---
    {"name": "iaa", "tier": "figures", "approx": "~3 MB",
     "patterns": ["experiments/cot_audit/data/sample_n500_traces.jsonl",
                  "experiments/cot_audit/outputs/iaa_n500_new/*.jsonl"],
     "consumers": ["tab_iaa"]},
    {"name": "slopegraph_inputs", "tier": "figures", "approx": "~1 MB",
     "patterns": ["neurips/defense_first_token_auroc_v2.json",
                  "neurips/defense_asr_orr_table_soft.json"],
     "consumers": ["fig_training_slopegraph"]},
]


def _tiers_at(tier: str) -> set[str]:
    return {"figures"} if tier == "figures" else {"figures", "full"}


def patterns_for(tier: str) -> list[str]:
    keep = _tiers_at(tier)
    pats: list[str] = []
    for b in MANIFEST:
        if b["tier"] in keep:
            pats.extend(b["patterns"])
    return pats


def print_manifest() -> None:
    print(f"Artifact tree -> {ARTIFACTS_ROOT}\n")
    for tier in ("figures", "full"):
        print(f"[{tier}]")
        for b in MANIFEST:
            if b["tier"] == tier:
                print(f"  {b['name']:22s} {b['approx']:>10s}  ->  {', '.join(b['consumers'])}")
        print()


def fetch(tier: str = "figures", repo: str | None = None) -> None:
    repo = repo or DEFAULT_REPO
    if repo.startswith("PLACEHOLDER"):
        raise SystemExit(
            "No artifact repo configured yet.\n"
            "Set the HuggingFace repo id once the bundle is uploaded:\n"
            "  export LRM_SAFETY_ARTIFACTS_REPO=<org>/<name>\n"
            "  python -m lrm_safety_deliberation.fetch_artifacts --tier " + tier + "\n"
            "or point LRM_SAFETY_ARTIFACTS at an existing artifact tree to skip the download."
        )
    try:
        from huggingface_hub import snapshot_download
    except ImportError as exc:
        raise SystemExit("huggingface_hub is required: pip install huggingface-hub") from exc

    ARTIFACTS_ROOT.mkdir(parents=True, exist_ok=True)
    print(f"Downloading '{tier}' tier from {repo} -> {ARTIFACTS_ROOT}")
    snapshot_download(
        repo_id=repo, repo_type="dataset",
        local_dir=str(ARTIFACTS_ROOT),
        allow_patterns=patterns_for(tier),
    )
    print("done.")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--tier", choices=["figures", "full"], default="figures")
    ap.add_argument("--repo", default=None, help="HuggingFace dataset repo id (overrides env)")
    ap.add_argument("--list", action="store_true", help="print the artifact manifest and exit")
    args = ap.parse_args()
    if args.list:
        print_manifest()
        return
    fetch(args.tier, args.repo)


if __name__ == "__main__":
    main()
