"""
STAIR Stage 2a (post): Extract step-level DPO preference pairs from MCTS trees.

Reads the tree data generated by generate_mcts.py and constructs
(chosen, rejected) pairs at each reasoning step node, based on the
value difference between sibling nodes.

Adapted from defenses/stair_repo/src/generate_actor_traindata.py.

Output: JSONL with {prompt, chosen, rejected, chosen_score, rejected_score, ...}
"""

import os
import json
import argparse
import random
import queue
import threading

from tqdm import tqdm
from transformers import AutoTokenizer


def trajectory_to_response(trajectory):
    return "".join(trajectory)


def extract_pairs_step_level(tree_data, args, tokenizer, output_list):
    """
    Extract step-level DPO pairs from MCTS tree data.

    For each internal node, compare sibling children:
    - chosen: child with higher value (above good_value_threshold)
    - rejected: child with lower value (delta > v_threshold)
    """
    for d in tqdm(tree_data, desc="Extracting DPO pairs"):
        tags = queue.Queue()
        tags.put("0")
        prompt = d["0"]["prompt"]

        while not tags.empty():
            tag = tags.get()
            responses = []
            values = []
            is_terminal = []
            visited_times = []

            for i in range(args.max_child_num):
                idx = f"{tag}.{i}"
                if idx in d:
                    value = d[idx]["true_value"]
                    if value is None:
                        continue
                    response = trajectory_to_response(d[idx]["trajectory"])
                    tokens = tokenizer(response, add_special_tokens=False, return_tensors="pt")
                    length = len(tokens["input_ids"][0])

                    if length <= args.max_tokens:
                        tags.put(idx)
                        if d[idx]["is_terminal"] or d[idx]["visited_times"] >= args.min_visit_times:
                            responses.append(response)
                            values.append(value)
                            is_terminal.append(d[idx]["is_terminal"])
                            visited_times.append(d[idx]["visited_times"])

            n = len(responses)
            for i in range(n):
                for j in range(n):
                    if (values[i] - values[j] > args.v_threshold
                            and values[i] >= args.good_value_threshold):
                        output_list.append({
                            "prompt": prompt,
                            "chosen": responses[i],
                            "rejected": responses[j],
                            "chosen_score": values[i],
                            "rejected_score": values[j],
                            "chosen_is_terminal": is_terminal[i],
                            "rejected_is_terminal": is_terminal[j],
                            "chosen_visited_times": visited_times[i],
                            "rejected_visited_times": visited_times[j],
                        })


def extract_pairs_terminal_only(tree_data, args, tokenizer, output_list):
    """
    Extract DPO pairs using only terminal nodes (complete trajectories).
    """
    for d in tqdm(tree_data, desc="Extracting terminal DPO pairs"):
        tags = queue.Queue()
        tags.put("0")
        prompt = d["0"]["prompt"]

        right_answers = []
        wrong_answers = []

        while not tags.empty():
            tag = tags.get()
            for i in range(args.max_child_num):
                idx = f"{tag}.{i}"
                if idx in d:
                    response = trajectory_to_response(d[idx]["trajectory"])
                    tokens = tokenizer(response, add_special_tokens=False, return_tensors="pt")
                    length = len(tokens["input_ids"][0])

                    if length <= args.max_tokens:
                        tags.put(idx)
                        if d[idx]["is_terminal"]:
                            reward = d[idx]["reward"]
                            if reward is None:
                                continue
                            if reward >= args.good_value_threshold:
                                right_answers.append((
                                    response, d[idx]["visited_times"], reward
                                ))
                            elif reward <= args.good_value_threshold - args.v_threshold:
                                wrong_answers.append((
                                    response, d[idx]["visited_times"], reward
                                ))

        if not right_answers or not wrong_answers:
            continue

        random.shuffle(right_answers)
        random.shuffle(wrong_answers)

        # Balance the pair counts
        if len(right_answers) < len(wrong_answers):
            factor = min(len(wrong_answers) // len(right_answers) + 1, args.max_gb_ratio)
            right_answers *= factor
        else:
            factor = min(len(right_answers) // len(wrong_answers) + 1, args.max_gb_ratio)
            wrong_answers *= factor

        for i in range(min(len(right_answers), len(wrong_answers))):
            output_list.append({
                "prompt": prompt,
                "chosen": right_answers[i][0],
                "rejected": wrong_answers[i][0],
                "chosen_score": right_answers[i][2],
                "rejected_score": wrong_answers[i][2],
                "chosen_is_terminal": True,
                "rejected_is_terminal": True,
                "chosen_visited_times": right_answers[i][1],
                "rejected_visited_times": wrong_answers[i][1],
            })


def main():
    parser = argparse.ArgumentParser(
        description="Extract DPO pairs from MCTS trees"
    )
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--mcts_path", required=True, type=str,
                        help="Path to MCTS tree JSON")
    parser.add_argument("--output_path", required=True, type=str,
                        help="Output JSONL path for DPO pairs")
    parser.add_argument("--tokenizer_path", required=True, type=str,
                        help="Tokenizer path (same as actor model)")
    parser.add_argument("--terminal_only", action="store_true",
                        help="Use only terminal nodes for pairs")
    parser.add_argument("--v_threshold", type=float, default=0.5,
                        help="Min value delta for pair construction")
    parser.add_argument("--good_value_threshold", type=float, default=0.8,
                        help="Min value for chosen node")
    parser.add_argument("--max_tokens", type=int, default=4096,
                        help="Max tokens for a trajectory to be included")
    parser.add_argument("--max_child_num", type=int, default=4,
                        help="Max children per node in tree")
    parser.add_argument("--min_visit_times", type=int, default=4,
                        help="Min visits for non-terminal node")
    parser.add_argument("--max_gb_ratio", type=int, default=4,
                        help="Max ratio between good and bad in terminal mode")
    parser.add_argument("--num_workers", type=int, default=32,
                        help="CPU worker threads for extraction")

    args = parser.parse_args()
    random.seed(args.seed)

    print(f"Loading MCTS data from {args.mcts_path}")
    with open(args.mcts_path) as f:
        mcts_data = json.load(f)
    print(f"Loaded {len(mcts_data)} trees")

    tokenizer = AutoTokenizer.from_pretrained(args.tokenizer_path, trust_remote_code=True)

    # Extract pairs using multi-threading for speed
    num_workers = args.num_workers
    partial_outputs = [[] for _ in range(num_workers)]
    worker_size = (len(mcts_data) + num_workers - 1) // num_workers
    threads = []

    extract_fn = extract_pairs_terminal_only if args.terminal_only else extract_pairs_step_level

    for i in range(num_workers):
        start = i * worker_size
        end = min((i + 1) * worker_size, len(mcts_data))
        worker_data = mcts_data[start:end]
        if not worker_data:
            continue
        t = threading.Thread(
            target=extract_fn,
            args=(worker_data, args, tokenizer, partial_outputs[i]),
        )
        threads.append(t)
        t.start()

    for t in threads:
        t.join()

    # Merge
    all_pairs = []
    for partial in partial_outputs:
        all_pairs.extend(partial)

    print(f"Extracted {len(all_pairs)} DPO pairs")

    # Statistics
    tt = sum(1 for p in all_pairs if p["chosen_is_terminal"] and p["rejected_is_terminal"])
    tn = sum(1 for p in all_pairs if p["chosen_is_terminal"] != p["rejected_is_terminal"])
    nn = sum(1 for p in all_pairs if not p["chosen_is_terminal"] and not p["rejected_is_terminal"])
    print(f"  Terminal-Terminal: {tt}")
    print(f"  Terminal-NonTerminal: {tn}")
    print(f"  NonTerminal-NonTerminal: {nn}")

    # Save
    os.makedirs(os.path.dirname(args.output_path), exist_ok=True)
    with open(args.output_path, "w") as f:
        for pair in all_pairs:
            f.write(json.dumps(pair, ensure_ascii=False) + "\n")

    print(f"Saved to {args.output_path}")


if __name__ == "__main__":
    main()
